import './globals.css'
import { TodoProvider } from './Todos.context'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <TodoProvider>
    <html lang="en">
    

      <body>{children}</body>
  

    </html>
    </TodoProvider>
  )
}
